### PR TITLE
CB_MAP: Allows no-clustering with max_cluster_radius == 0px

### LINKED ISSUE #733: Map Clustering can not be disabled
**Describe the bug**
The map clusters the markers based on some settings. To disable this, the tooltip mentions to set the value to "0".

When I do this and save the page, I get the error, that the value "0" is not allowed:

As a workaround I set the value to 10 px, but I consider this as a bug.

### PR DESCRIPTION
**Pull request by datengraben**
This fixes getBounds error when max_cluster_radius is set to 0px, by computing `center_position` from the average lat/lon of all markers.

This will resolve #733 

I tested it with my local setup, with 3 locations there is no problem (See issue discussion).

I don't know about performance issue when there are many more markers to display.

When you accept it I will remove the debug logs.

### CODE REVIEW

File: assets/map/js/cb-map-shortcode.js [hunk 1]
```diff
@@ -117,10 +117,12 @@ function CB_Map() {
 
         var markers;
 
-        // @TODO: Check real problem with markers.getBounds() error.
-        if(!this.settings.max_cluster_radius || this.settings.max_cluster_radius <= 0) {
+        console.log('max_cluster_radius - Was ' + this.settings.max_cluster_radius)
```
Comment (hansmorb) [inline assets/map/js/cb-map-shortcode.js:120]: Können die console logs noch weg? Das wäre super!

**Review by hansmorb — CHANGES_REQUESTED** [review]

File: assets/map/js/cb-map-shortcode.js (hunk 1 above)
Comment (datengraben) [reply assets/map/js/cb-map-shortcode.js]: Sind weg.

**Comment by datengraben** [comment]
Can you squash the commits? I don't see something I can configure (for example like in Gitlab).

Prefered commit message for this branch would be:
```
CB_MAP: Fix allows no-clustering with max_cluster_radius == 0px

Covers the case of center_position === undefined.
Why or when center_position is undefined, I don't know at the moment.
So this is rather a small fix
```
